export const actionTypes = {
  // Products
  FETCH_PRODUCTS : "FETCH_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  FETCH_PRODUCT_BY_CATEGORY: "FETCH_PRODUCT_BY_CATEGORY",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",

  // Categories
  FETCH_CATEGORY : "FETCH_CATEGORY",
  FETCH_CATEGORIES : "FETCH_CATEGORIES",

  // Users
  SET_USER : "SET_USER",
  UPDATE_USER : "UPDATE_USER",
  GET_USER : "GET_USER",

  // Orders
  SET_ORDER : "SET_ORDER",
  FETCH_ORDERS : "FETCH_ORDERS",
  UPDATE_QTY : "UPDATE_QTY",
  UPDATE_STATUS : "UPDATE_STATUS",
  FETCH_ORDERS_WHERE_USERID : "FETCH_ORDERS_WHERE_USERID",
  FETCH_ORDERS_SELLER : "FETCH_ORDERS_SELLER",
  DELETE_ORDER_DETAILS : "DELETE_ORDER_DETAILS",
  FETCH_ORDERS_BY_ID : "FETCH_ORDERS_BY_ID",
  FETCH_PAYMENT : "FETCH_PAYMENT",

  // Colors
  FETCH_COLORS : "FETCH_COLORS",

  // Address
  SET_MODALS : "SET_MODALS",
  SET_ADDRESS : "SET_ADDRESS",
  GET_ADDRESS : "GET_ADDRESS",
  GET_ADDRESS_BY_ID : "GET_ADDRESS_BY_ID",
}