export const actionTypes = {
  // Products
  FETCH_PRODUCTS : "FETCH_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  FETCH_PRODUCT_BY_CATEGORY: "FETCH_PRODUCT_BY_CATEGORY",

  // Categories
  FETCH_CATEGORY : "FETCH_CATEGORY",
  FETCH_CATEGORIES : "FETCH_CATEGORIES"
}